#!/bin/bash --login
#$ -cwd
#$ -t 1-13206
#$ -N cgroup

line=`awk "NR==$SGE_TASK_ID" matchtable.txt`
#1-13206
# Set tab as the delimiter

IFS=$'\t' read -a strarr <<< "${line}"
declare -p strarr
#Read the split line into an array based on tab delimiter
# Get the size of the variable
size=${#strarr[*]} 
echo $size
# Store centroid name
centroid_name="centroid_${strarr[0]}"
echo $centroid_name
i=0

if [ -e $centroid_name.fasta ]
then
	rm $centroid_name.fasta
fi

while [ $i -ne $size ]
do
	i=$(($i+1))
	# Get genome prefix
	genome=$(echo ${strarr[i]} | cut -d"_" -f1)
	gene_id=$(echo ${strarr[i]} | cut -d"_" -f2)
	genome_path="/mnt/iusers01/pb01/f99731hc/scratch/imperial/Afum/${genome}"
	# Check whether a linear file exists
	if [ ! -e $genome_path/linear_nuc_seq.fna ]
	then
		# Remove blank spaces
		sed '/^$/d' $genome_path/nuc_seq.fna > $genome_path/clean_nuc_seq.fna
		# Linearise
		awk '{if(NR==1) {print $0} else {if($0 ~ /^>/) {print "\n"$0} else {printf $0}}}' $genome_path/clean_nuc_seq.fna > $genome_path/linear_nuc_seq.fna
	
	fi
	# Write gene to centroid file
	grep -A1 ">${gene_id}_g" $genome_path/linear_nuc_seq.fna | sed "s/>${gene_id}_g/>${genome}_${gene_id}_g/g" >> $centroid_name.fasta
		
	
done
