#!/bin/bash --login
#$ -cwd
#$ -N para_blastp
#$ -pe smp.pe 10
#$ -t 1-218
FOLDER=`awk "NR==$SGE_TASK_ID" folder_paths.txt`
PREFIX=$(echo $FOLDER | rev | cut -d"/" -f1 | rev | cut -d"." -f1)
echo $PREFIX
module load apps/binapps/anaconda3/2020.07
conda activate blast_env
PROTEIN="${FOLDER}/${PREFIX}.pep.fa"
# Run all-vs-all BLAST
blastp -db pep_blast_db -query $PROTEIN -outfmt "6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore" -out "${PREFIX}_v_all.tsv" -max_hsps 1 -num_threads $NSLOTS 
