#!/bin/bash --login
#$ -cwd
#$ -N para_blastbuild
#$ -pe smp.pe 10
module load apps/binapps/anaconda3/2020.07
conda activate blast_env
LOGDATE=25_11_21
# Extract individual protein and attribute files and combine for PanOCT input
while read line 
do
PROTEIN=$(echo "${line}/${PREFIX}.masked.pep.fa")
ATTR=$(echo "${line}/${PREFIX}_attr.txt")
cat $PROTEIN >> ~/scratch/imperial/all_$LOGDATE.pep.fa
cat $PROTEIN >> ~/scratch/imperial/all_attr_$LOGDATE.txt
done <folder_paths.txt

# Once all files have been combined, generate BLAST DB
if [ ! -f pep_blast_db.00.phr ]
then
    makeblastdb -in all.pep.fa -dbtype prot -out pep_blast_db
else
	rm -r pep_blast_db*
	makeblastdb -in all_$LOGDATE.pep.fa -dbtype prot -out pep_blast_db
fi



