#!/bin/bash --login
#$ -cwd
#$ -t 1-1
#$ -N recallc30
#$ -pe smp.pe 12
module load apps/binapps/anaconda3/2020.07
module load tools/env/proxy2 

conda activate imperial

FOLDER=`awk "NR==$SGE_TASK_ID" c30_path.txt`

# Enter the isolate folder
cd $FOLDER
# Extract prefix
PREFIX=$(echo $FOLDER | rev | cut -d"/" -f1 | rev)
echo $PREFIX

#### ANNOTATION ####
# Predict protein coding sequences using ProtHint
conda activate prothint_env
mkdir recall_ep
export PATH="/mnt/iusers01/pb01/f99731hc/ProtHint/dependencies/GeneMarkES/gmes_linux_64/:$PATH"
python ~/ProtHint/bin/prothint.py --threads $NSLOTS --fungus ./mask_$PREFIX/$PREFIX.contigs.fa.masked ~/scratch/imperial/proteins.fasta
# Make gene calls using GeneMark-EP+
~/gmes_linux_64/gmes_petap.pl --cores $NSLOTS --EP prothint.gff --evidence evidence.gff --max_intron 200 --max_intergenic 100000 --sequence ./mask_$PREFIX/$PREFIX.contigs.fa.masked --min_contig=10000 --fungus --work-dir ./recall_ep

#### EXTRACT GENE FASTA ####
conda activate gffread_env
# Replace " " in GTF chromosome name with "_"
awk 'BEGIN{FS=OFS="\t"} {gsub(/ /, "_", $1)} 1' ./recall_ep/genemark.gtf > ./recall_ep/updated_masked_genemark.gtf
# Do the same for the genome
sed 's/ /_/g' ./mask_$PREFIX/$PREFIX.contigs.fa.masked > ./recall_ep/updated_masked_$PREFIX.contigs.fa
# Extract the transcripts with gffread
gffread -w ./recall_ep/$PREFIX.masked.transcripts.fa -g ./updated_masked_$PREFIX.contigs.fa ./recall_ep/updated_masked_genemark.gtf

#### CONVERT GENE TO PEP ####
conda activate emboss_env
transeq -sequence ./recall_ep/$PREFIX.masked.transcripts.fa -outseq ./recall_ep/$PREFIX.masked.pep.fa
# Remove asterisks
sed -i 's/*//g' ./recall_ep/$PREFIX.masked.pep.fa

GENES=$(grep -c ">" ./recall_ep/$PREFIX.masked.transcripts.fa)
