#!/bin/bash --login
#$ -cwd
#$ -t 1-218
#$ -N table
module load apps/binapps/anaconda3/2020.07
module load tools/env/proxy2 



FOLDER=`awk "NR==$SGE_TASK_ID" folder_paths.txt`

# Enter the isolate folder
cd $FOLDER
# Extract prefix
PREFIX=$(echo $FOLDER | rev | cut -d"/" -f1 | rev)
SIZE=$(grep 'Main genome scaffold sequence total:' $PREFIX.stats | cut -d$'\t' -f2)
N50=$(grep 'Main genome contig N/L50:' $PREFIX.stats | cut -d"/" -f3)
CONTIG=$(grep 'Main genome contig total:' $PREFIX.stats | cut -d$'\t' -f2)

echo "${PREFIX},${SIZE},${CONTIG},${N50}" >> ~/scratch/imperial/stats.table


