#!/bin/bash --login
#$ -cwd
#$ -N oct
#$ -pe smp.pe 32
#$ -l mem1500  
#$ -M harry.chown@postgrad.manchester.ac.uk
#$ -m e
#$ -hold_jid para_blastp
#module load apps/binapps/anaconda3/2020.07
#module load tools/env/proxy2

# Combine all BLAST outputs
if [-e ~/scratch/imperial/tab_blast.tsv]
then 
	rm tab_blast.tsv
else
	echo "Generating new files"
fi

while read line 
do
PREFIX=$(echo $line | rev | cut -d"/" -f1 | rev)
BLAST=$(echo "${line}/${PREFIX}_v_all.tsv")
cat $BLAST >> ~/scratch/imperial/tab_blast.tsv
done <folder_paths.txt

conda activate panoct_env
~/panoct_v3.23/bin/panoct.pl -t ~/scratch/imperial/tab_blast.tsv -f ~/scratch/imperial/all_tag_$LOGDATE.txt -g ~/scratch/imperial/all_attr_$LOGDATE.txt -P ~/scratch/imperial/all_$LOGDATE.pep.fa -S Y -L 1 -M Y -H Y -V Y -N Y -F 1.33 -G y -c 0,25,50,75,100 -T
